# Site settings
title: PAPERFIVE
email: ""
description: "Online Sejak 2018"
url: "https://bagassaadillah.github.io"
baseurl: "/paperfive"
facebook_username: "bagassaadillah12"
twitter_username: "bagassaadillah"
instagram_username: "storepaperfive"
github_username:  "bagassaadillah"
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   Bagas Saadillah Arkan
  avatar: bagas_avatar.png
  favicon: favicon.ico
  info: found…ôr of @storepaperfive 

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://bagassaadillah.github.io/paperfive/gallery/"  
  - JOURNAL: "https://bagassaadillah.github.io/paperfive/journal/"
  - ABOUT: "https://bagassaadillah.github.io/paperive/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
